import localFont from "next/font/local";
import "./globals.css";
import SideBar from "./components/SideBar";
import MyProvider from "./context/SideBar";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#79a6ff27] antialiased`}
      >
        <Toaster/>
        <MyProvider>
          <div className="w-screen flex p-2 relative">
            <SideBar />
            <div className="w-full md:pl-[255px]">{children}</div>
          </div>
        </MyProvider>
      </body>
    </html>
  );
}
